version: "3"

services:
  api-server:
    build:
      context: ./contentbotapi/
    container_name: api-server
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./contentbotapi/:/api
    command: > 
      bash -c
      "python3 manage.py makemigrations
      &&python3 manage.py migrate
      &&python3 manage.py runserver 0.0.0.0:8000"
  pars-app:
    build:
      context: ./contentbotparser/
    container_name: pars-app
    restart: always
    ports:
      - "8001:8001"
    command: >
      bash -c
      "go run cmd/main.go"
    volumes:
      - ./contentbotparser/:/pars/
    environment:
      - API_SERVER=http://api-server:8000/api/
  tg_bot:
    build:
      context: ./contentbottelegram/
    container_name: tg-bot
    restart: always
    ports:
      - "7000:7000"
    command: >
      bash -c
      "go run cmd/main.go"
    volumes:
      - ./contentbottelegram/:/tg-bot/
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"




